name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract version from Git tag
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Determine tags for Docker image
      run: |
        if [ "${{ github.ref }}" != "" ]; then
          echo "TAGS=dayaron/disneyworld-metrics-datadog:${{ env.VERSION }},dayaron/disneyworld-metrics-datadog:latest" >> $GITHUB_ENV
        else
          echo "TAGS=dayaron/disneyworld-metrics-datadog:develop" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.TAGS }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
