name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Prepare tags
      run: |
        if [[ ${{ github.ref }} == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          TAGS="dayaron/disneyworld-metrics-datadog:$VERSION,dayaron/disneyworld-metrics-datadog:latest"
        elif [[ ${{ github.ref }} == refs/heads/develop ]]; then
          TAGS="dayaron/disneyworld-metrics-datadog:develop"
        else
          # This branch should not be reached due to the workflow's 'on' conditions, but it's here as a safeguard.
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          TAGS="dayaron/disneyworld-metrics-datadog:unexpected-$TIMESTAMP"
          echo "Unexpected ref ${GITHUB_REF}, using timestamp for tag."
        fi
        echo "TAGS=$TAGS" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.TAGS }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7