name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract version from Git tag
      id: extract_version
      run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/tags/})"
      if: startsWith(github.ref, 'refs/tags/')

    - name: Determine tags for Docker image
      id: docker_tags
      run: |
        if [[ "${{ steps.extract_version.outputs.version }}" != "" ]]; then
          echo "::set-output name=tags::dayaron/disneyworld-metrics-datadog:${{ steps.extract_version.outputs.version }},dayaron/disneyworld-metrics-datadog:latest"
        else
          echo "::set-output name=tags::dayaron/disneyworld-metrics-datadog:develop"
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_tags.outputs.tags }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
